CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('Alumno','Docente','Administrativo')),
    estado VARCHAR2(20) DEFAULT 'Activo' CHECK (estado IN ('Activo','Bloqueado'))
);

CREATE TABLE ejemplares (
    id_ejemplar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    autor VARCHAR2(150),
    editorial VARCHAR2(100),
    anio NUMBER(4),
    categoria VARCHAR2(50),
    estado VARCHAR2(20) DEFAULT 'Disponible' CHECK (estado IN ('Disponible','Prestado','Baja'))
);

CREATE TABLE prestamos (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_ejemplar NUMBER NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE,
    fecha_devolucion DATE,
    devuelto CHAR(1) DEFAULT 'N' CHECK (devuelto IN ('S','N')),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_prestamo_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES ejemplares(id_ejemplar)
);

CREATE TABLE reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_ejemplar NUMBER NOT NULL,
    fecha_reserva DATE DEFAULT SYSDATE,
    CONSTRAINT fk_reserva_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_reserva_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES ejemplares(id_ejemplar)
);

CREATE TABLE multas (
    id_multa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    monto NUMBER(6,2) NOT NULL,
    pagado CHAR(1) DEFAULT 'N' CHECK (pagado IN ('S','N')),
    fecha_multa DATE DEFAULT SYSDATE,
    CONSTRAINT fk_multa_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE INDEX idx_prestamos_usuario ON prestamos(id_usuario);
CREATE INDEX idx_prestamos_ejemplar ON prestamos(id_ejemplar);
CREATE INDEX idx_reservas_usuario ON reservas(id_usuario);
CREATE INDEX idx_reservas_ejemplar ON reservas(id_ejemplar);